- name: restart vault-agent
  become: True
  service:
    daemon_reload: yes
    name: vault-agent
    state: restarted
    enabled: yes

- name: reload timer
  become: True
  systemd:
    daemon_reload: yes
    name: vault-cafix.timer
    enabled: yes
    state: started

- name: reload restart timer
  become: True
  systemd:
    daemon_reload: yes
    name: vault-agent-restart.timer
    enabled: yes
    state: started
